In [1]:
import pandas as pd

import os
import pathlib

In [2]:
root = os.getcwd()
src_root = os.path.join(root, 'csv')
src_root = pathlib.Path(src_root)
assert os.path.exists(src_root)
dst_dir = os.path.join(root, 'timeseries_by_attribute')

if not os.path.exists(dst_dir):
    os.makedirs(dst_dir)

# Taking all other folders than ipynb checkpoints
dirs = [item for item in src_root.iterdir() if not 'ipynb' in item.stem]

In [3]:
for directory in dirs:
    stem = directory.stem
    files = [item for item in directory.iterdir() if not 'ipynb' in item.stem]

    dfs = []

    for file in files:
        df = pd.read_csv(file)
        df['date'] = pd.to_datetime(df['date']) 
        df = df.set_index('date')
        dfs.append(df)
    result = pd.concat(dfs)
    result = result.sort_index()
    dst_path = os.path.join(dst_dir, stem + '.csv')
    result.to_csv(dst_path)

In [32]:
directory = dirs[1]
stem = directory.stem
files = [item for item in directory.iterdir() if not 'ipynb' in item.stem]

dfs = []

for file in files:
    df = pd.read_csv(file)
    df['date'] = pd.to_datetime(df['date']) 
    df = df.set_index('date')
    dfs.append(df)
result = pd.concat(dfs)
result = result.sort_index()
dst_path = os.path.join(dst_dir, stem + '.csv')
result.to_csv(dst_path)

In [31]:
result

,996,1003,1008,1009,1012,1014,1015,1018,1019,1021,...,937,941,943,946,951,961,964,1369,1366,1357
date,,,,,,,,,,,,,,,,,,,,,
1962-02-01,0.52,0.58,0.51,0.51,0.50,0.43,0.53,0.52,0.46,0.44,...,0.63,0.59,0.58,0.56,0.53,0.45,0.45,0.41,0.40,0.35
1962-02-02,0.25,0.30,0.26,0.26,0.25,0.21,0.26,0.25,0.23,0.20,...,0.35,0.35,0.35,0.33,0.30,0.21,0.19,0.22,0.22,0.08
1962-02-03,0.14,0.08,0.07,0.07,0.07,0.08,0.10,0.10,0.09,0.08,...,0.09,0.07,0.07,0.06,0.05,0.02,0.06,0.16,0.17,-0.01
1962-02-04,0.21,0.19,0.20,0.20,0.20,0.23,0.20,0.20,0.21,0.23,...,0.16,0.14,0.14,0.14,0.14,0.15,0.21,0.15,0.15,0.12
1962-02-05,0.12,0.09,0.12,0.12,0.12,0.16,0.11,0.11,0.16,0.17,...,0.11,0.15,0.15,0.14,0.14,0.16,0.15,0.11,0.12,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-27,-0.04,-0.04,-0.05,-0.05,-0.06,-0.06,-0.05,-0.05,-0.04,-0.05,...,-0.03,-0.01,-0.02,-0.03,-0.04,-0.07,-0.08,-0.01,-0.01,-0.04
2021-03-28,0.06,0.05,0.04,0.04,0.04,0.04,0.05,0.05,0.05,0.04,...,0.07,0.09,0.09,0.07,0.07,0.05,0.02,-0.02,-0.02,0.14
2021-03-29,-0.09,0.05,0.04,0.04,0.03,-0.03,-0.02,-0.02,-0.07,-0.11,...,0.09,0.15,0.14,0.12,0.11,0.09,0.05,0.13,0.13,0.23
2021-03-30,0.52,0.57,0.43,0.43,0.41,0.24,0.47,0.46,0.32,0.12,...,0.69,0.71,0.69,0.63,0.56,0.29,0.22,0.32,0.37,0.27
2021-03-31,0.44,0.41,0.39,0.39,0.39,0.40,0.41,0.41,0.45,0.41,...,0.45,0.45,0.45,0.44,0.42,0.36,0.36,0.45,0.45,0.58

In [25]:
dst_path

'/home/iielse/Documents/DIWA/data/copernicus_climate/timeseries_by_attribute/snow_evaporation.csv'